import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'dayjs/locale/pt-br'
import dayjs from 'dayjs'
import { Providers } from './providers'
import { ColorSchemeScript } from '@mantine/core'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  dayjs.locale('pt-BR')
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${inter.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
